MK_CFG_DIR = /home/z/share/make_cfg
include $(MK_CFG_DIR)/make.defs

LIBNAME = ncore
LIBVERSION=1
CSRC = uni_util.c str_util.c base64.c urlsafe_base64.c url_codec.c chpipe.c

WARN +=
OPPFLAGS +=
LDFLAGS =
LDLIBS =

include $(MK_CFG_DIR)/make.rules
